### ISSUE TITLE
能设 proxy 吗

### ISSUE THREAD

**Issue by mgcyung** [AllTheLife/Bard.el#4]

**Comment by was0A** [comment]
这个我还没想好怎么实现，目前能想到的是等 google 在 api 中提供 proxy 支持

具体进度参见：https://github.com/google/generative-ai-python/issues/188

不知道其他大佬有什么思路？🤔

**Comment by mgcyung** [comment]
#6 Mac + Emacs 28.2 测试可用

**Comment by perlinson** [comment]
[lighthulb-hikari ](https://github.com/tandemdude/hikari-lightbulb) 这个库 可以通过以下方式通过代理访问discord 
proxy_settings = hikari.impl.ProxySettings(
    url=PROXY,  # Replace with your proxy URL
    # trust_env=True
)
bot = lightbulb.BotApp(token=TOKEN, 
                       prefix=lightbulb.when_mentioned_or(None), 
                       default_enabled_guilds=1208370626016841788,
                       logs="DEBUG",
                       proxy_settings=proxy_settings,
                       )
       不知道对你有帮助不
